year= input("Enter the year: ")
genre = input("Enter the genre: ")
album = input("Enter the album: " )
title = input("Enter the song title: ")
artist = input("Enter the artist: ")

print("----------------------------------------")
print("SONG DETAILS")
print("----------------------------------------")

print("Enter the year: ",year)
print("Enter the genre: ", genre)
print("Enter the album: ", album)
print("Enter the song title: ", title)
print("Enter the arist: ", artist)